/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [ID]
      ,[Name]
      ,[Sex]
      ,[Age]
      ,[Height]
      ,[Weight]
      ,[NOC]
      ,[Games]
      ,[City]
      ,[Sport]
      ,[Event]
      ,[Medal]
  FROM [olympic_games].[dbo].[athletes_event_results] 